language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec
 
deploy:
 provider: heroku
 api_key: 166d6cff-eafc-4c64-9238-61b82eb45656
 app: agile-lowlands-89868
 run: "heroku rake db:migrate"
 on:
  all_branches: true